= Couchbase Lite with React Native on iOS
:snippet: {attachmentsdir}/HotelFinder/ios/HotelFinder/

In this tutorial, you will learn how to use Couchbase Lite in a React Native project.

The sample project in this tutorial is an application that can search for hotels.
Each hotel can be bookmarked or unbookmarked.

image::https://via.placeholder.com/700x300?text=App+Screenshots+Placeholder[]

In this application, the User Interface is written in JavaScript and Data Persistence is written in Swift with Couchbase Lite's API.
This architecture allows you to write the User Interface code once for both iOS and Android whilst keeping the benefits of using Couchbase Lite for data management.

== How to Complete this Tutorial

*The User Interface has already been implemented in the starter project.
You will add the code to persist and query data.*

. Download the link:{attachmentsdir}/starter-project.zip[starter project].
. Unzip *starter-project.zip*.
. Run the following commands in your Terminal.
+
[source,bash]
----
cd HotelFinder
npm install -g react-native-cli
npm install
react-native link
npm run start
----
The `npm run start` command runs in the background.
It starts a web server to bundle and serve the JavaScript code to the application.
You should see the following in the output.
+
[source,bash]
----
Metro Bundler ready.

Loading dependency graph...
----
. Open the Xcode project at *HotelFinder/ios/HotelFinder.xcodeproj*.
. Build and run.
. You can click on the *Hotels* button to run a search query.
But the result of the query is empty because the application is missing the code to persist data.

In the next section, you will setup the Native Module interface which is the first step for establishing communication between native code and JavaScript.

== Native Modules Setup

With https://facebook.github.io/react-native/docs/0.56/native-modules-ios[Native Modules], you can write native code and have access to it from JavaScript.
It is helpful when an app needs access to native APIs, and React Native doesn't have a corresponding module yet.
In this tutorial, you will use the Native Modules API to implement methods in Swift and call them from the JavaScript code.
These methods will do the following:

- Search for terms in a Couchbase Lite database.
- Query documents in a Couchbase Lite database.
- Create and Update documents in a Couchbase Lite database.

=== Swift/Objective-C Setup

. Select the kbd:[File > New > File... > Objective-C File] menu and create a new file called *RCTBridge.m*.
. Insert the following in *RCTBridge.m*.
+
[source,swift]
----
#import <Foundation/Foundation.h>
#import "React/RCTBridgeModule.h"

@interface RCT_EXTERN_MODULE(HotelFinderNative, NSObject)

/* code will be added here later. */

+ (BOOL)requiresMainQueueSetup
{
  return YES;
}
@end
----
. Select the kbd:[File > New > File... > Objective-C File] menu and create a new file called *HotelFinderNative.swift*.
. Insert the following in *HotelFinderNative.swift*.
+
[source,swift]
----
import Foundation

@objc (HotelFinderNative)
class HotelFinderNative: NSObject {

	/* code will be added here later. */

}
----

You are now ready to implement functionalities in Swift.
The next step is to import the Couchbase Lite framework in your project.

== Couchbase Lite Setup

. Download Couchbase Lite from https://www.couchbase.com/downloads[here].
. Unzip the file and drag *CouchbaseLiteSwift.framework* over the Xcode project navigator.
. Navigate to *Project > General > Embedded Binary* and drag *CouchbaseLiteSwift.framework* over to this section.
+
image::https://via.placeholder.com/700x200?text=Drag+To+Embedded+Frameworks[]
. Import the Swift framework in *HotelFinderNative.swift*.
+
[source,swift]
----
import CouchbaseLiteSwift
----

== Database Setup

In our example, we will start with a pre-built Couchbase Lite database that contains a bunch of documents.
We will make our queries against the documents in this database.
Note that in a real world application, the data could be synced down from other Couchbase Lite clients or from Sync Gateway in the cloud.

The pre-built database needs to be added to the Xcode project.

. Download link:{attachmentsdir}/travel-sample.cblite2.zip[travel-sample.cblite2.zip] and drag it over the Xcode project navigator.
Make sure to select the *Copy items if needed* checkbox.
. Next, you will use an instance variable to open and access the database.
In *HotelFinderNative.swift*, replace the `/* code will be added here later. */` comment with the following lines.
+
[source,swift]
----
include::{examplesdir}/HotelFinder/ios/HotelFinder/HotelFinderNative.swift[tag=lazy-database,indent=0]
----
In this code, you first check if a database named "travel-sample" exists.
If it doesn't exist, the bundled database file is copied to the default Couchbase Lite directory.
The database is then opened and the instance returned.
The `createIndexes` method will be implemented in the next step.
. In *HotelFinderNative.swift*, add the following method.
This method creates the Full-Text Search index on the `description` property.
+
[source,swift]
----
include::{examplesdir}/HotelFinder/ios/HotelFinder/HotelFinderNative.swift[tag=create-indexes,indent=0]
----
. Build & run. The project should build successfully.

In the next sections, you will use this instance variable to perform various operations.

== Search Hotels

In this section, you will add the functionality to search for hotels.

. Add the following to the top of *HotelFinder/Hotels.js*.
+
[source,javascript]
----
include::{examplesdir}/HotelFinder/Hotels.js[tag=import-statement,indent=0]
----
. Next, you must implement the new method in the `HotelFinderNative` module before it can be accessed in JavaScript.
Insert a new method signature in *RCTBridge.m*.
+
[source,objectivec]
----
include::{examplesdir}/HotelFinder/ios/HotelFinder/RCTBridge.m[tag=search-hotels-method-signature,indent=0]
----
`RCT_EXPORT_METHOD()` is a React Native macro to specify that this method must be exported to JavaScript.
. Implement this method in *HotelFinderNative.swift*.
+
[source,swift]
----
include::{examplesdir}/HotelFinder/ios/HotelFinder/HotelFinderNative.swift[tag=search-hotels-method-impl,indent=0]
----
. Add the following to the `onChangeText` method in *Hotels.js*.
+
[source,javascript]
----
include::{examplesdir}/HotelFinder/Hotels.js[tag=search-hotels-js,indent=0]
----
. Build & run.
. Enter "UK" in the location input field and press the *Lookup* button.
You should now see a list of hotels in the search result.
+
image::https://via.placeholder.com/300x400?text=Demo+Search+Results[]

== Bookmark Hotel

. Insert a new method signature in *RCTBridge.m*.
+
[source,objectivec]
----
include::{examplesdir}/HotelFinder/ios/HotelFinder/RCTBridge.m[tag=bookmark-method-signature,indent=0]
----
. Implement this method in *HotelFinderNative.swift*.
+
[source,swift]
----
include::{examplesdir}/HotelFinder/ios/HotelFinder/HotelFinderNative.swift[tag=bookmark-method-swift,indent=0]
----
. Add the following to the `bookmarkHotel` method in *Hotel.js*.
+
[source,javascript]
----
include::{examplesdir}/HotelFinder/Hotels.js[tag=bookmark-method-js,indent=0]
----
. Build & run.
. Click *Hotels* and search for a hotel (type "UK" in the location field for example).
. You can now swipe a table view row to bookmark a hotel.
+
image::https://via.placeholder.com/300x400?text=Demo+Swipe+Row[]

In the next section, you will query the bookmarked hotels to display them on the first screen.

== Bookmarked Hotels List

. Add the following to the top of *HotelFinder/BookmarkedHotels.js*.
+
[source,swift]
----
include::{examplesdir}/HotelFinder/BookmarkedHotels.js[tag=import-statement,indent=0]
----
. Insert a new method signature in *RCTBridge.m*.
+
[source,objectivec]
----
include::{examplesdir}/HotelFinder/ios/HotelFinder/RCTBridge.m[tag=bookmark-list-signature,indent=0]
----
. Implement this method in *HotelFinderNative.swift*.
+
[source,swift]
----
include::{examplesdir}/HotelFinder/ios/HotelFinder/HotelFinderNative.swift[tag=bookmark-list-method-swift,indent=0]
----
. Add the following to the `queryBookmarkedHotels` method in *BookmarkedHotels.js*.
+
[source,javascript]
----
include::{examplesdir}/HotelFinder/BookmarkedHotels.js[tag=bookmark-list-method-js,indent=0]
----
. Build and run.
. You can now see the hotel that was bookmarked in the <<bookmark-hotel, Bookmark Hotel>> section show up on the Bookmarked hotels screen.
+
image::https://via.placeholder.com/300x400?text=Demo+Bookmarked+List[]

////
== Unbookmark Hotel

. Insert a new method signature in `RCTBridge.m`.
+
[source,objectivec]
----
include::{examplesdir}/HotelFinder/ios/HotelFinder/RCTBridge.m[tag=unbookmark-method-signature,indent=0]
----
. Implement this method in `HotelFinderNative.swift`.
+
[source,swift]
----
include::{examplesdir}/HotelFinder/ios/HotelFinder/HotelFinderNative.swift[tag=unbookmark-method-swift,indent=0]
----
. Add the following to the `unbookmarkHotel` method in *Hotels.js*.
+
[source,javascript]
----
include::{examplesdir}/HotelFinder/Hotels.js[tag=unbookmark-method-js,indent=0]
----
////

== Conclusion

Well done, you learned how to import Couchbase Lite in a React Native project to add search and persistence functionalities to your application!
You can find a working copy of the end result in the link:{attachmentsdir}/final-project.zip[final project] zip file.